import { Hotel } from '../domain/types'

export const hotelsMock: Hotel[] = [
  {
    id: '1',
    city: 'Якутск',
    name: 'Гостиница "Северное сияние"',
    rating: 4.5,
    pricePerNight: 3500,
    description: 'Уютная гостиница в центре города с видом на реку. Бесплатный Wi-Fi, парковка.',
    distanceFromCenter: 0.5,
    hasBreakfast: false,
    hasParking: true,
  },
  {
    id: '2',
    city: 'Якутск',
    name: 'Отель "Якутск Плаза"',
    rating: 4.8,
    pricePerNight: 5200,
    description: 'Современный отель с комфортабельными номерами и рестораном. Рядом с главными достопримечательностями.',
    distanceFromCenter: 1.2,
    hasBreakfast: true,
    hasParking: true,
  },
  {
    id: '3',
    city: 'Якутск',
    name: 'Гостевой дом "Тайга"',
    rating: 4.2,
    pricePerNight: 2800,
    description: 'Тихий гостевой дом в типичном якутском стиле. Завтрак включен.',
    distanceFromCenter: 2.5,
    hasBreakfast: true,
    hasParking: false,
  },
  {
    id: '4',
    city: 'Москва',
    name: 'Отель "Столичный"',
    rating: 4.7,
    pricePerNight: 6500,
    description: 'Элегантный отель в центре Москвы. Рядом с метро и основными достопримечательностями.',
    distanceFromCenter: 0.8,
    hasBreakfast: true,
    hasParking: true,
  },
  {
    id: '5',
    city: 'Москва',
    name: 'Гостиница "Красная площадь"',
    rating: 4.6,
    pricePerNight: 5800,
    description: 'Комфортабельная гостиница в историческом центре. Вид на Кремль.',
    distanceFromCenter: 1.5,
    hasBreakfast: true,
    hasParking: false,
  },
  {
    id: '6',
    city: 'Москва',
    name: 'Отель "Метрополь"',
    rating: 4.9,
    pricePerNight: 8500,
    description: 'Роскошный отель в самом центре Москвы. Премиум-услуги, спа-центр.',
    distanceFromCenter: 0.2,
    hasBreakfast: true,
    hasParking: true,
  },
  {
    id: '7',
    city: 'Санкт-Петербург',
    name: 'Отель "Нева"',
    rating: 4.9,
    pricePerNight: 7200,
    description: 'Роскошный отель на набережной Невы. Панорамный вид на город.',
    distanceFromCenter: 0.3,
    hasBreakfast: true,
    hasParking: true,
  },
  {
    id: '8',
    city: 'Санкт-Петербург',
    name: 'Мини-отель "Петроградский"',
    rating: 4.3,
    pricePerNight: 4200,
    description: 'Уютный мини-отель в историческом районе. Идеально для туристов.',
    distanceFromCenter: 2.1,
    hasBreakfast: false,
    hasParking: false,
  },
  {
    id: '9',
    city: 'Санкт-Петербург',
    name: 'Гостиница "Невский проспект"',
    rating: 4.4,
    pricePerNight: 4800,
    description: 'Комфортабельная гостиница на главной улице города. Рядом с метро.',
    distanceFromCenter: 0.6,
    hasBreakfast: true,
    hasParking: false,
  },
  {
    id: '10',
    city: 'Новосибирск',
    name: 'Гостиница "Сибирь"',
    rating: 4.4,
    pricePerNight: 3800,
    description: 'Современная гостиница в деловом центре города. Конференц-залы, ресторан.',
    distanceFromCenter: 1.0,
    hasBreakfast: true,
    hasParking: true,
  },
  {
    id: '11',
    city: 'Новосибирск',
    name: 'Отель "Обь"',
    rating: 4.1,
    pricePerNight: 3200,
    description: 'Уютный отель с видом на реку Обь. Бесплатный Wi-Fi, парковка.',
    distanceFromCenter: 1.8,
    hasBreakfast: false,
    hasParking: true,
  },
  {
    id: '12',
    city: 'Казань',
    name: 'Отель "Кремль"',
    rating: 4.6,
    pricePerNight: 4500,
    description: 'Отель в историческом центре Казани. Рядом с Кремлём и главными достопримечательностями.',
    distanceFromCenter: 0.7,
    hasBreakfast: true,
    hasParking: true,
  },
  {
    id: '13',
    city: 'Казань',
    name: 'Гостиница "Волга"',
    rating: 4.1,
    pricePerNight: 3200,
    description: 'Уютная гостиница с видом на Волгу. Бесплатный Wi-Fi.',
    distanceFromCenter: 2.3,
    hasBreakfast: false,
    hasParking: true,
  },
  {
    id: '14',
    city: 'Екатеринбург',
    name: 'Отель "Урал"',
    rating: 4.5,
    pricePerNight: 4000,
    description: 'Современный отель в центре Екатеринбурга. Конференц-залы, фитнес-центр.',
    distanceFromCenter: 0.9,
    hasBreakfast: true,
    hasParking: true,
  },
  {
    id: '15',
    city: 'Екатеринбург',
    name: 'Мини-отель "Центральный"',
    rating: 4.0,
    pricePerNight: 2900,
    description: 'Небольшой уютный отель в центре города. Идеально для бизнес-поездок.',
    distanceFromCenter: 1.8,
    hasBreakfast: false,
    hasParking: false,
  },
  {
    id: '16',
    city: 'Сочи',
    name: 'Отель "Чёрное море"',
    rating: 4.7,
    pricePerNight: 6800,
    description: 'Роскошный отель на берегу Чёрного моря. Собственный пляж, спа-центр.',
    distanceFromCenter: 0.4,
    hasBreakfast: true,
    hasParking: true,
  },
  {
    id: '17',
    city: 'Сочи',
    name: 'Гостиница "Приморская"',
    rating: 4.2,
    pricePerNight: 4800,
    description: 'Комфортабельная гостиница рядом с морем. Завтрак включен.',
    distanceFromCenter: 1.2,
    hasBreakfast: true,
    hasParking: false,
  },
  {
    id: '18',
    city: 'Краснодар',
    name: 'Отель "Кубань"',
    rating: 4.4,
    pricePerNight: 3600,
    description: 'Современный отель в центре Краснодара. Ресторан, парковка.',
    distanceFromCenter: 0.6,
    hasBreakfast: true,
    hasParking: true,
  },
  {
    id: '19',
    city: 'Владивосток',
    name: 'Отель "Тихий океан"',
    rating: 4.6,
    pricePerNight: 5500,
    description: 'Отель с видом на Тихий океан. Современные номера, ресторан морепродуктов.',
    distanceFromCenter: 0.5,
    hasBreakfast: true,
    hasParking: true,
  },
  {
    id: '20',
    city: 'Владивосток',
    name: 'Гостиница "Портовая"',
    rating: 4.0,
    pricePerNight: 3400,
    description: 'Уютная гостиница рядом с портом. Идеально для деловых поездок.',
    distanceFromCenter: 1.5,
    hasBreakfast: false,
    hasParking: true,
  },
  {
    id: '21',
    city: 'Нижний Новгород',
    name: 'Отель "Волжский берег"',
    rating: 4.3,
    pricePerNight: 3900,
    description: 'Отель на берегу Волги. Комфортабельные номера, ресторан.',
    distanceFromCenter: 0.8,
    hasBreakfast: true,
    hasParking: false,
  },
  {
    id: '22',
    city: 'Нижний Новгород',
    name: 'Гостиница "Кремль"',
    rating: 4.5,
    pricePerNight: 4100,
    description: 'Гостиница в историческом центре. Рядом с Кремлём и главными достопримечательностями.',
    distanceFromCenter: 0.4,
    hasBreakfast: true,
    hasParking: true,
  },
  {
    id: '23',
    city: 'Ростов-на-Дону',
    name: 'Отель "Дон"',
    rating: 4.4,
    pricePerNight: 3700,
    description: 'Современный отель в центре Ростова. Конференц-залы, фитнес-центр.',
    distanceFromCenter: 0.7,
    hasBreakfast: true,
    hasParking: true,
  },
  {
    id: '24',
    city: 'Ростов-на-Дону',
    name: 'Мини-отель "Центральный"',
    rating: 4.1,
    pricePerNight: 3000,
    description: 'Небольшой уютный отель в центре города. Бесплатный Wi-Fi.',
    distanceFromCenter: 1.3,
    hasBreakfast: false,
    hasParking: false,
  },
  {
    id: '25',
    city: 'Самара',
    name: 'Отель "Волга"',
    rating: 4.5,
    pricePerNight: 4200,
    description: 'Отель на набережной Волги. Панорамный вид, ресторан.',
    distanceFromCenter: 0.5,
    hasBreakfast: true,
    hasParking: true,
  },
  {
    id: '26',
    city: 'Самара',
    name: 'Гостиница "Центральная"',
    rating: 4.2,
    pricePerNight: 3500,
    description: 'Комфортабельная гостиница в центре города. Рядом с метро.',
    distanceFromCenter: 0.9,
    hasBreakfast: true,
    hasParking: false,
  },
  {
    id: '27',
    city: 'Уфа',
    name: 'Отель "Башкирия"',
    rating: 4.3,
    pricePerNight: 3800,
    description: 'Современный отель в столице Башкортостана. Ресторан, парковка.',
    distanceFromCenter: 0.6,
    hasBreakfast: true,
    hasParking: true,
  },
  {
    id: '28',
    city: 'Уфа',
    name: 'Гостевой дом "Урал"',
    rating: 4.0,
    pricePerNight: 2900,
    description: 'Уютный гостевой дом. Тихий район, бесплатный Wi-Fi.',
    distanceFromCenter: 2.0,
    hasBreakfast: false,
    hasParking: false,
  },
]

