export { AalLogoIcon } from './aal-logo-icon'
export { RouteIcon } from './route-icon'
export { HotelIcon } from './hotel-icon'
export { CarIcon } from './car-icon'
export { ServicesIcon } from './services-icon'
export { MammothIcon } from './mammoth-icon'
export { MammothMascotIcon } from './mammoth-mascot-icon'
export { HeartIcon } from './heart-icon'
export { ProfileIcon } from './profile-icon'
export { SettingsIcon } from './settings-icon'
export { default as VkIcon } from './vk-icon'
export { default as OkIcon } from './ok-icon'
export { default as TelegramIcon } from './telegram-icon'

