-- Migration 007: Cleanup virtual data and invalid references
-- Purpose: Remove all virtual stops/routes, invalid references, and old generated data
-- This migration prepares the database for a clean rebuild with corrected logic

-- ============================================================================
-- SECTION 1: Delete all virtual stops
-- ============================================================================

/**
 * Delete all virtual stops
 * These will be regenerated by VirtualEntitiesGeneratorWorker with corrected logic
 */
DELETE FROM virtual_stops;

COMMENT ON TABLE virtual_stops IS 'Virtual stops will be regenerated by VirtualEntitiesGeneratorWorker after cleanup';

-- ============================================================================
-- SECTION 2: Delete all virtual routes
-- ============================================================================

/**
 * Delete all virtual routes
 * These will be regenerated by VirtualEntitiesGeneratorWorker with corrected logic
 */
DELETE FROM virtual_routes;

COMMENT ON TABLE virtual_routes IS 'Virtual routes will be regenerated by VirtualEntitiesGeneratorWorker after cleanup';

-- ============================================================================
-- SECTION 3: Delete flights with invalid route references
-- ============================================================================

/**
 * Delete flights that reference non-existent routes
 * These flights cannot be used in graph building
 */
DELETE FROM flights
WHERE route_id IS NOT NULL
  AND route_id NOT IN (SELECT id FROM routes);

-- ============================================================================
-- SECTION 4: Delete routes with invalid stop references
-- ============================================================================

/**
 * Delete routes that reference non-existent stops
 * These routes cannot be used in graph building
 */
DELETE FROM routes
WHERE from_stop_id NOT IN (SELECT id FROM stops)
   OR to_stop_id NOT IN (SELECT id FROM stops);

-- ============================================================================
-- SECTION 5: Delete routes and flights created by generators (before fixes)
-- ============================================================================

/**
 * Delete routes created by AirRouteGeneratorWorker (before fixes)
 * These routes may have invalid stop references or incorrect structure
 * Routes from mock data (route-001 to route-041) are preserved
 */
DELETE FROM routes
WHERE id LIKE 'air-route-%'
   OR id LIKE 'virtual-route-%'
   OR id LIKE 'virtual-route-connectivity-%';

/**
 * Delete flights associated with deleted routes
 */
DELETE FROM flights
WHERE route_id LIKE 'air-route-%'
   OR route_id LIKE 'virtual-route-%'
   OR route_id LIKE 'virtual-route-connectivity-%';

-- ============================================================================
-- SECTION 6: Delete all datasets
-- ============================================================================

/**
 * Delete all dataset versions
 * New dataset will be created by ODataSyncWorker with corrected data
 */
DELETE FROM datasets;

COMMENT ON TABLE datasets IS 'Datasets will be regenerated by ODataSyncWorker after cleanup';

-- ============================================================================
-- SECTION 7: Delete all graphs
-- ============================================================================

/**
 * Delete all graph metadata
 * New graph will be built by GraphBuilderWorker with corrected data
 */
DELETE FROM graphs;

COMMENT ON TABLE graphs IS 'Graphs will be regenerated by GraphBuilderWorker after cleanup';

-- ============================================================================
-- SECTION 8: Delete routes/flights referencing virtual-stop----------------
-- ============================================================================

/**
 * Delete routes that reference the invalid virtual-stop----------------
 * This stop was created with empty cityName and is invalid
 */
DELETE FROM routes
WHERE from_stop_id LIKE 'virtual-stop-%'
   OR to_stop_id LIKE 'virtual-stop-%';

/**
 * Delete flights that reference routes with virtual-stop----------------
 */
DELETE FROM flights
WHERE route_id IN (
  SELECT id FROM routes
  WHERE from_stop_id LIKE 'virtual-stop-%'
     OR to_stop_id LIKE 'virtual-stop-%'
);

-- ============================================================================
-- SECTION 9: Cleanup summary
-- ============================================================================

/**
 * After this migration:
 * - Only real stops from mock data remain (stops table)
 * - Only real routes from mock data remain (routes table: route-001 to route-041)
 * - Only real flights from mock data remain (flights table)
 * - All virtual entities are removed
 * - All datasets are removed
 * - All graphs are removed
 * - Invalid references are cleaned up
 * 
 * Next steps:
 * 1. ODataSyncWorker will load stops/routes/flights from mock data
 * 2. AirRouteGeneratorWorker will create air routes with valid stops
 * 3. VirtualEntitiesGeneratorWorker will create virtual stops/routes with corrected logic
 * 4. GraphBuilderWorker will build graph with all corrected data
 */

-- ============================================================================
-- Migration Complete
-- ============================================================================

COMMENT ON SCHEMA public IS 'Cleaned up virtual data and invalid references - Migration 007';

