import type { BaseEntity } from './BaseEntity';
import type { TransportType } from './Route';

/**
 * Flight entity - represents a scheduled flight (real or virtual)
 * 
 * Stores all flights (both real from OData and virtual generated) with schedule information.
 * Real flights updated by Worker 1, virtual flights generated by Worker 2.
 * 
 * @example
 * ```typescript
 * const flight = new Flight({
 *   id: 'flight-yak-001-monday-08:00',
 *   routeId: 'route-yakutsk-moscow',
 *   fromStopId: 'yakutsk-airport',
 *   toStopId: 'moscow-airport',
 *   departureTime: '08:00',
 *   arrivalTime: '14:00',
 *   daysOfWeek: [1, 2, 3, 4, 5], // Mon-Fri
 *   priceRub: 15000,
 *   transportType: 'PLANE',
 *   isVirtual: false
 * });
 * ```
 */
export class Flight implements BaseEntity {
  constructor(
    public readonly id: string,
    public readonly fromStopId: string,
    public readonly toStopId: string,
    public readonly departureTime: string, // HH:MM format
    public readonly arrivalTime: string, // HH:MM format
    public readonly daysOfWeek: number[], // 1-7 (Monday-Sunday)
    public readonly routeId?: string, // NULL for virtual flights
    public readonly priceRub?: number,
    public readonly isVirtual: boolean = false,
    public readonly transportType?: TransportType,
    public readonly metadata?: Record<string, unknown>,
    public readonly createdAt?: Date
  ) {
    this.validate();
  }

  /**
   * Validates the entity
   */
  private validate(): void {
    if (!this.id || this.id.trim().length === 0) {
      throw new Error('Flight: id is required');
    }

    if (!this.fromStopId || this.fromStopId.trim().length === 0) {
      throw new Error('Flight: fromStopId is required');
    }

    if (!this.toStopId || this.toStopId.trim().length === 0) {
      throw new Error('Flight: toStopId is required');
    }

    if (!this.isValidTime(this.departureTime)) {
      throw new Error(`Flight: invalid departureTime ${this.departureTime}`);
    }

    if (!this.isValidTime(this.arrivalTime)) {
      throw new Error(`Flight: invalid arrivalTime ${this.arrivalTime}`);
    }

    if (this.daysOfWeek.length === 0) {
      throw new Error('Flight: daysOfWeek cannot be empty');
    }

    if (this.daysOfWeek.some(day => day < 1 || day > 7)) {
      throw new Error('Flight: daysOfWeek must be between 1 and 7');
    }

    if (this.priceRub !== undefined && this.priceRub < 0) {
      throw new Error('Flight: priceRub must be non-negative');
    }
  }

  /**
   * Validates time format (HH:MM)
   */
  private isValidTime(time: string): boolean {
    const regex = /^([0-1][0-9]|2[0-3]):([0-5][0-9])$/;
    return regex.test(time);
  }

  /**
   * Converts time string to minutes since midnight
   */
  private timeToMinutes(time: string): number {
    const [hours, minutes] = time.split(':').map(Number);
    return hours * 60 + minutes;
  }

  /**
   * Calculates duration in minutes
   * Handles overnight flights (arrival time < departure time)
   */
  public getDurationMinutes(): number {
    const depMinutes = this.timeToMinutes(this.departureTime);
    const arrMinutes = this.timeToMinutes(this.arrivalTime);

    if (arrMinutes >= depMinutes) {
      return arrMinutes - depMinutes;
    } else {
      // Overnight flight
      return 1440 - depMinutes + arrMinutes; // 1440 = 24 * 60
    }
  }

  /**
   * Checks if this is an overnight flight
   */
  public isOvernightFlight(): boolean {
    const depMinutes = this.timeToMinutes(this.departureTime);
    const arrMinutes = this.timeToMinutes(this.arrivalTime);
    return arrMinutes < depMinutes;
  }

  /**
   * Checks if flight operates on specific day
   * @param dayOfWeek 1-7 (Monday-Sunday)
   */
  public operatesOnDay(dayOfWeek: number): boolean {
    return this.daysOfWeek.includes(dayOfWeek);
  }

  /**
   * Checks if flight operates on specific date
   */
  public operatesOnDate(date: Date): boolean {
    const dayOfWeek = date.getDay() === 0 ? 7 : date.getDay(); // Sunday is 7, not 0
    return this.operatesOnDay(dayOfWeek);
  }

  /**
   * Gets days of week as readable strings
   */
  public getDaysAsStrings(): string[] {
    const dayNames = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
    return this.daysOfWeek.map(day => dayNames[day - 1]);
  }

  /**
   * Checks if flight operates daily
   */
  public isDaily(): boolean {
    return this.daysOfWeek.length === 7;
  }

  /**
   * Checks if flight operates on weekdays only
   */
  public isWeekdaysOnly(): boolean {
    return (
      this.daysOfWeek.length === 5 &&
      this.daysOfWeek.every(day => day >= 1 && day <= 5)
    );
  }

  /**
   * Checks if flight operates on weekends only
   */
  public isWeekendsOnly(): boolean {
    return (
      this.daysOfWeek.length === 2 &&
      this.daysOfWeek.includes(6) &&
      this.daysOfWeek.includes(7)
    );
  }

  /**
   * Converts to plain object for serialization
   */
  public toJSON(): Record<string, unknown> {
    return {
      id: this.id,
      routeId: this.routeId,
      fromStopId: this.fromStopId,
      toStopId: this.toStopId,
      departureTime: this.departureTime,
      arrivalTime: this.arrivalTime,
      daysOfWeek: this.daysOfWeek,
      priceRub: this.priceRub,
      isVirtual: this.isVirtual,
      transportType: this.transportType,
      metadata: this.metadata,
      createdAt: this.createdAt?.toISOString()
    };
  }
}




